interledgerjs/ilp-connector

lib/ledgers/five-bells-ledger.js, services/config.js
Requires https://github.com/interledger/five-bells-shared/pull/34
=> [FEATURE] Add admin

.dockerignore, Dockerfile, README.md, apidoc.json, app.js, backends/fixerio/index.js, controllers/notifications.js, controllers/payments.js, controllers/quote.js, index.js, lib/payments.js, package.json, services/backend.js, services/config.js, test/notificationSpec.js, test/paymentSpec.js, test/services/backend.js, test/services/config.js
Pretty much what it says on the tin.
Breaking change in that the config variables now have a different prefix.
=> Rename trader -> connector

lib/ledgers/five-bells-ledger.js
Requires https://github.com/interledger/five-bells-ledger/pull/84 and https://github.com/interledger/five-bells-shared/pull/42
=> [FIX] s/identity/connector

errors/assets-not-traded-error.js, errors/external-error.js, errors/funds-not-held-error.js, errors/insufficient-fee-error.js, errors/many-to-many-not-supported-error.js, errors/no-amount-specified-error.js, errors/no-related-destination-debit-error.js, errors/no-related-source-credit-error.js, errors/unacceptable-conditions-error.js, errors/unacceptable-expiry-error.js, errors/unacceptable-rate-error.js, errors/unrelated-notification-error.js, errors/unrelated-payment-error.js
=> Convert error classes to es6

lib/payments.js, lib/testPaymentExpiry.js, package.json, test/data/paymentOneToOneAtomic.json, test/data/paymentOneToOneAtomic_TwoCases.json, test/paymentSpec.js
Requires https://github.com/interledger/five-bells-shared/pull/44
=> [FEATURE] Support Cases; refactor expiry validation

backends/fixerio/index.js, controllers/quote.js, test/quoteSpec.js
Depends on https://github.com/interledger/five-bells-shared/pull/45 and https://github.com/interledger/five-bells-ledger/pull/106
Fixes https://github.com/interledger/five-bells-connector/issues/51
Fixes https://github.com/interledger/five-bells-connector/issues/50
Based on https://github.com/interledger/five-bells-connector/pull/59
=> [FEATURE] payment template

controllers/quote.js, errors/unacceptable-amount-error.js, lib/balance-cache.js, services/balance-cache.js, test/balanceCacheSpec.test.js, test/quoteSpec.js
Check liquidity before returning a quote. Error if the balance isn't high
enough. Quoting doesn't actually escrow any funds, so no error is not a guarantee
that a transfer preparation will succeed, and an error is not a guarantee that
it wouldn't.
Fixes #60 
Based on https://github.com/interledger/five-bells-connector/pull/61
=> [FEATURE] /quote: add liquidity check

lib/ledgers/five-bells-ledger.js
=> Include auth in subscription requests

lib/ledgers/five-bells-ledger.js
If the account doesn't exist yet, it can't be subscribed to, so autofund first.
This is necessary to fix the visualization. /cc @MatthewPhinney
=> [FIX] create+fund account before subscribing

lib/ledgers/five-bells-ledger.js, package.json
Depends on https://github.com/interledger/five-bells-shared/pull/55
Send `password_hash` to be compatible with the latest ledger.
=> [TASK] hashPassword

src/lib/payments.js
=> [FIX] use new config

src/backends/fixerio/index.js
In response to @clark800 in https://github.com/interledger/five-bells-connector/pull/80#discussion_r53208799
=> Don't use reassignment in quote rounding

package.json, src/app.js, src/index.js, src/services/auth.js
Depends on https://github.com/interledger/five-bells-connector/pull/83
=> Add client cert middleware and auth service

README.md, package.json, src/lib/config.js, src/lib/ledgers/five-bells-ledger.js, test/configSpec.js
Note: autofunding only used for testing purposes
=> Allow using TLS cert credentials for admin account (autofund feature)

bin/bump.sh, package.json
Adds `npm run bump` which will:
1) Check we're on master
2) Check local is in sync with remote (not diverged, ahead or behind)
2a) Print a list of the commits since the last released version
3) Bump version locally, commit and tag
4) Push commit and tags to remote
=> Use a script to bump a version and push to master

src/lib/balance-cache.js, src/lib/config.js, src/lib/ledgers/five-bells-ledger.js, test/configSpec.js
=> FIX: Check for key or password

src/controllers/payments.js, src/controllers/quote.js, src/lib/subscriber.js, test/balanceCacheSpec.test.js, test/configSpec.js, test/healthSpec.js, test/metadataSpec.js, test/notificationSpec.js, test/paymentSpec.js, test/quoteSpec.js
Spacing after * for generator functions
=> Fix lint errors

package.json, src/backends/fixerio/index.js, src/backends/ilp-quoter/index.js, src/controllers/pairs.js, src/index.js, src/lib/ledgers/five-bells-ledger.js, src/lib/ledgers/multiledger.js, src/lib/payments.js, src/services/balance-cache.js, src/services/settlementQueue.js, test/configSpec.js, test/paymentSpec.js
Includes breaking change:
https://github.com/interledger/five-bells-shared/commit/9d32aadb4fb9e5affca688efeeda0724fbd66479
=> Update five-bells-shared to v12.1.0

src/backends/fixerio/index.js, src/models/quote.js, test/notificationSpec.js, test/quoteSpec.js
Requires the ledger to support returning its precision
https://github.com/interledger/five-bells-ledger/commit/87f8622e25ae2b0d3ea9c39d7284c00aaa5b4e83
TODO:
- Caching ledger precision
=> BREAKING | FEATURE: Get precision from ledger

src/backends/ilp-quoter/index.js
=> Fix 500 error on quote request for disallowed pair

schemas/PositiveFiniteAmount.json, schemas/Quote.json, src/backends/fixerio/index.js, src/backends/ilp-quoter/index.js, src/backends/utils.js, src/controllers/quote.js, src/errors/invalid-amount-specified-error.js, src/lib/executeSourceTransfers.js, src/lib/ledgers/five-bells-ledger.js, src/lib/validate.js, src/models/quote.js, test/quoteSpec.js
- Move common quote methods to `utils`. 
- Return 422 on quote with unsupported currency pair
=> Quote with unsupported ledger should return 422

package.json, src/app.js
Ledger [allows CORS](https://github.com/interledger/five-bells-ledger/blob/master/src/lib/app.js#L38) but the connector does not
=> [FEATURE] Enable CORS

README.md, package.json, src/app.js, src/controllers/quote.js, src/lib/config.js, src/models/metadata.js, src/models/quote.js, test/metadataSpec.js, test/quoteSpec.js
Corresponding sender changes: https://github.com/interledger/five-bells-sender/pull/56
This isn't breaking because its behind a feature flag by default.
=> [FEATURE] move pathfinder to connector

package.json, src/lib/ledgers/five-bells-ledger.js, src/lib/ledgers/multiledger.js, src/models/subscriptions.js
Subscribes to websocket notifications instead of REST hooks.
Depends on interledger/five-bells-ledger#236
=> Use new websocket notification feature

.gitignore, circle.yml, scripts/publish_web.js
This will auto-update the API documentation on interledger.org.
=> Auto-publish gh-pages

src/lib/testPaymentExpiry.js, test/data/paymentOptimistic.json, test/notificationSpec.js
Fixes https://github.com/interledger/five-bells-connector/issues/153
=> [FIX] Fix optimistic mode expiry validation

src/backends/ilp-quoter/index.js
Cherry pick from `ilp_server_alpha` branch
=> Passing additional info from quoter backend

package.json, src/models/subscriptions.js, test/mocks/mockPlugin.js, test/paymentsSpec.js, test/subscriptionSpec.js
* Depends on https://github.com/interledger/js-ilp-plugin-bells/pull/20
* Part of https://github.com/interledger/five-bells-connector/issues/198
=> fix: assume transfer.ledger property is assigned by plugins

src/models/subscriptions.js, test/paymentsSpec.js
Reject the source transfer when an outgoing transfer is rejected.
=> fix: relay outgoing_reject

src/lib/routing-tables.js, src/services/routing-tables.js, test/helpers/app.js, test/routeBroadcasterSpec.js, test/routeBuilderSpec.js, test/routingTablesSpec.js
=> fix: don't shift the Route for the trivial rate

package.json
=> chore: update ilp-plugin-virtual

scripts/ci-deploy.sh
=> chore: fix docker script (again)

Dockerfile, circle.yml, package.json
Updates the node version used in the `Dockerfile`.
=> Fix: update node version in docker to 6

src/controllers/routes.js, src/lib/route-broadcaster.js
Gives an INFO message whenever a peer is added, a new route is added, or routes are broadcasted
=> feat: add more logging of new routes and peers

README.md
Add a little more to the README.
=> docs: document the CONNECTOR_PEERS field better

src/app.js, src/common/log.js
For consistency with interledgerjs/five-bells-ledger#356
=> Add a prefix to log messages

src/lib/route-broadcaster.js
For https://github.com/interledger/rfcs/pull/126
Depends on https://github.com/interledgerjs/ilp-plugin-bells/pull/71
=> feat: ignore NoSubscriptionsError

schemas/PositiveFiniteAmount.json, src/models/quote.js, test/quoteSpec.js
Fixes https://github.com/interledgerjs/ilp-connector/issues/262
=> fix: fix Quote.json schema

src/app.js, src/models/subscriptions.js, test/paymentsSpec.js, test/subscriptionSpec.js
Fixes https://github.com/interledgerjs/ilp-connector/issues/257
cc: @justmoon @vhpoet
=> fix: initialize the plugins without using pairs

src/lib/route-broadcaster.js, test/mocks/mockPlugin.js, test/quoteSpec.js
Fixes https://github.com/interledgerjs/ilp-connector/issues/261
=> fix: don't broadcast routes to self when missing username

src/lib/route-broadcaster.js, test/routeBroadcasterSpec.js
the connector was waiting for all messages to be delivered before
continuing to broadcast routes. this was discovered because
ilp-plugin-virtual's sendMessage was hanging and this was preventing the
connector from broadcasting routes. this change makes the broadcast
function synchronous. we'll fire off each message but won't wait for the
promise to finish, since all we'll do is log an error if it rejects
anyway.
=> fix: don't wait for route broadcast message delivery

package.json, src/errors/ledger-not-connected-error.js, src/lib/route-builder.js, test/modifyPluginSpec.js, test/paymentsSpec.js, test/quoteSpec.js, test/routeBuilderSpec.js, test/subscriptionSpec.js
Depends on https://github.com/interledgerjs/ilp-plugin-bells/pull/79
Related to https://github.com/interledgerjs/ilp-connector/issues/248
=> feat: refuse to quote/settle when not connected

src/app.js
For the ILP Kit's peering functionality
=> Feat: expose core's getClient function

src/app.js
This gets done in `lib/core`, but wasn't happening in `addPlugin`.
=> Fix: create a store in addPlugin

src/lib/route-broadcaster.js
Fixes https://github.com/interledgerjs/ilp-connector/issues/285
=> fix: use setTimeout for route broadcasting

src/lib/route-broadcaster.js
Fixes https://github.com/interledgerjs/ilp-connector/issues/300
=> fix: use correct context in broadcastSoon

src/lib/ledgers.js, src/models/payments.js
Just two quick fixes to get settlement working
* Connector should not try to process payments addressed to itself (on the ledger it's receiving the money on)
* Connector should remove plugins correctly
=> Fixes for settlement

src/lib/pluginStore.js, test/storeSpec.js
To be extra sure that nothing bad can happen
=> Fix: validate table name in plugin store

src/errors/no-route-found-error.js, src/lib/message-router.js, src/lib/route-broadcaster.js, src/lib/route-builder.js, test/modifyPluginSpec.js, test/quoteSpec.js, test/routeBroadcasterSpec.js, test/routeBuilderSpec.js
Make it easier to debug the connector when it cannot find a route
=> feat: better errors and debug log when no route found

src/app.js, src/lib/route-broadcaster.js, test/routeBroadcasterSpec.js
Fixes https://github.com/interledgerjs/ilp-connector/issues/309
=> fix: don't block if initial connection fails

src/lib/route-broadcaster.js
+ use of .delete to remove added_during_epoch from the route json was causing it to be missing for later connectors in that broadcast round (this bug crept in during PR changes); this led to some connectors  (where there are >2 on a ledger) never receiving some routes.
+ new-route epoch logic was faulty, so that some routes were rebroadcast forever; previous tests weren't well designed to detect this (depends on https://github.com/interledgerjs/ilp-routing/pull/28 )
=> fix: route versioning

circle.yml
See https://circleci.com/gh/interledgerjs/ilp-connector
=> chore: use node 7

package.json, src/lib/message-router.js, src/lib/route-broadcaster.js, test/routeBroadcasterSpec.js
Implements https://github.com/interledgerjs/ilp-routing/issues/29
=> Don't broadcast peer routes

src/lib/route-builder.js, src/models/payments.js, test/paymentsSpec.js
- fixes the check if the connector is the payee
- does not throw an error if the connector payee
=> fix: fixes the check if the connector is the payee of a payment

src/app.js, src/lib/route-broadcaster.js
Fixes a bug that caused config routes to fail to load when route broadcasting was disabled. Fixes a bug that caused all config routes to have a 1:1 liquidity curve.
=> Fix configured routes

src/backends/one-to-one.js, src/lib/config.js
Passes the overrideInfo field through environment parsing. Also applies a fix to fixerio to the one-to-one backend.
=> Fix overrideInfo

src/backends/fixerio/index.js, src/backends/ilp-quoter/index.js, src/backends/one-to-one.js, test/ilpQuoterSpec.js, test/quoteSpec.js
Fixes https://github.com/interledgerjs/ilp-routing/issues/50
=> fix: adjust probeSourceAmount according to scales

package.json, test/quoteSpec.js
See https://github.com/interledgerjs/ilp-routing/pull/54
=> chore: ilp-routing@10.1.0

src/backends/fixerio/index.js, src/backends/one-to-one.js, test/helpers/app.js, test/mocks/mockPlugin.js, test/quoteSpec.js
=> fix: curve should be empty if connector is broke

package.json, src/app.js, src/backends/fixerio-plus-coinmarketcap.js, src/backends/fixerio-plus-xrp.js, src/backends/fixerio/index.js, src/backends/ilp-quoter/index.js, src/backends/one-to-one.js, src/lib/executeSourceTransfer.js, src/lib/ledgers.js, src/lib/message-router.js, src/lib/quoter.js, src/lib/route-broadcaster.js, src/lib/route-builder.js, src/lib/testPaymentExpiry.js, src/models/payments.js, src/models/subscriptions.js, test/configSpec.js, test/ilpQuoterSpec.js, test/mocha.opts, test/modifyPluginSpec.js, test/paymentsSpec.js, test/quoteSpec.js, test/routeBroadcasterSpec.js, test/routeBuilderSpec.js, test/routingTablesSpec.js, test/storeSpec.js, test/subscriptionSpec.js, test/tradingPairsSpec.js, wallaby.js
Bringing the connector codebase up-to-date with async/await.
=> refactor: generators -> async/await

src/lib/executeSourceTransfer.js, src/models/payments.js, src/models/subscriptions.js, test/subscriptionSpec.js
Pass fulfillment data, see interledger/rfcs#338.
=> Pass fulfillment data back

package.json, src/lib/route-builder.js, test/paymentsSpec.js, test/routeBuilderSpec.js
Follow-up to #397. Work in progress, tests are still failing.
=> feat: use forwarded payments

src/services/config.ts, src/services/route-broadcaster.ts
Both of these changes are needed to get the integration tests passing.
=> fix: handle "integer" config; relay broadcasts

src/middlewares/balance.ts
- Fixes the balance direction in log messages
- On outgoing data, do not adjust the balance on reject/error. This causes the connector to think its balance is artificially high, and leads to dispute with peers.
=> Fix: balance direction

src/backends/randomizer.ts, src/controllers/ilp-prepare.ts, src/services/middleware-manager.ts
=> Some changes for the demo today

src/services/route-broadcaster.ts
If both `sendRoutes` and `receiveRoutes` are false, don't send a route control message.
=> fix: don't send route control message if disabled

scripts/build_schema_types.js, src/errors/invalid-json-body-error.ts, src/middlewares/alert.ts, src/middlewares/balance.ts, src/schemas/BalanceUpdate.json, src/schemas/Config.json, src/services/admin-api.ts, src/services/middleware-manager.ts, src/types/middleware.ts, test/admin.test.js
Alerts are created when a peer unexpectedly returns a "maximum balance exceeded" error. They are accessible via the admin api. Also adds an endpoint to the admin API that allows the peer balances to be modified.
=> feat: admin-api: add alerting for unexpected T04

src/services/route-broadcaster.ts
These messages are way too noisy. When you have hundreds of clients connected you can't see anything else in the logs. Closes https://github.com/interledgerjs/ilp-connector/issues/438
=> Refactor: put route control on debug level

src/common/log.ts
Fixes errors with circleci. 
Also adds a comment on log usage in the constructor for it.
=> fix: linting

src/controllers/ilp-prepare.ts
Makes it easier to spot errors by printing the error code, triggeredBy, and message
=> Feat: log rejections

src/services/admin-api.ts, test/admin.test.js
Expose new functionality in the Admin API to add a plugin
=> feat: addAccount in admin API
