src/lib/executeSourceTransfers.js, src/lib/ledgers/five-bells-ledger.js, src/lib/ledgers/multiledger.js
https://github.com/interledger/five-bells-ledger/pull/133 broke the trader, this should make the compatible again.
=> [FIX] fix condition fulfillment

package.json, src/lib/balance-cache.js, src/lib/config.js, src/services/balance-cache.js, test/balanceCacheSpec.test.js, test/configSpec.js, test/notificationSpec.js, test/paymentSpec.js
[Update to use immutable config](https://github.com/interledger/five-bells-connector/pull/70/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L24) included a change that prevented co-mocha from ever executing the tests' generators. As a result, many test failures were going unreported. This remedies that issue, and fixes all of the tests that were broken by that patch and since.
/cc @lumberj
=> [FIX] use co-mocha, so that tests actually run

package.json, src/backends/fixerio/index.js, src/controllers/notifications.js, src/lib/executeSourceTransfers.js, src/lib/ledgers/five-bells-ledger.js, src/lib/ledgers/multiledger.js, src/lib/payments.js, src/services/destinationSubscriptions.js, test/data/notificationWithConditionFulfillment.json, test/notificationSpec.js, test/paymentSpec.js, test/quoteSpec.js
As of [five-bells-shared v9.2.0](https://github.com/interledger/five-bells-shared/commit/2ebbbbb5e15fd594a7ddd9eea4ffdd99e00f33e4) the `execution_condition_fulfillment` was moved from the transfer object to the notification. This updates the connector accordingly and fixes broken tests.
Fixes https://github.com/interledger/five-bells-connector/issues/79
=> Don't expect fulfillment in transfer

README.md, src/lib/ledgers/five-bells-ledger.js
Also, add fingerprint when autofunding an account (debug feature) so it works
with client cert auth
=> FIX: Pass username into client-cert credentials

src/models/payments.js, test/notificationSpec.js
Addresses RILP-362. I'm not sure how to test this now since the payments endpoint was removed.
=> Fix exception on payment that is missing the execution_condition

README.md, src/lib/config.js
Previously, CA file was only parsed correctly when using client cert
authentication.
This correctly parses the file, which is useful if using self-signed
certificates in testing environments
=> fix: allow using a CA with basic-auth credentials

src/app.js, src/backends/fixerio/index.js, src/backends/ilp-quoter/index.js, src/backends/one-to-one.js, src/common/health.js, src/controllers/health.js, src/lib/config.js, src/lib/ledgers/five-bells-ledger.js, src/lib/ledgers/multiledger.js, src/lib/route-broadcaster.js, src/services/route-broadcaster.js
* Check health of all ledgers before to start broadcasting routes
* /health endpoint now returns some actual status on the backend and the routing
=> Check ledgers' health before crawling / broadcasting routes

package.json, src/lib/ledgers/five-bells-ledger.js
Websocket was not reconnecting when one of the ledgers was going down, so all of the payments were getting expired after the ledger recovery.
=> WebSocket: Reconnect on disconnect

schemas/Quote.json, src/controllers/quote.js, src/lib/route-builder.js, src/models/quote.js, test/quoteSpec.js, test/routeBuilderSpec.js
Use the object found in `schemas/Quote.json` for Quotes instead of `Transfer`.
This will break any code that calls `/quote` directly.
The corresponding sender change is https://github.com/interledger/five-bells-sender/pull/69
=> [BREAKING] Dont use Transfers as Quotes

README.md, package.json, src/controllers/notifications.js, src/ledgers/five-bells-ledger.js, src/lib/route-builder.js, src/models/payments.js, test/data/notificationDestinationTransferAtomic_TwoCases.json, test/data/notificationDestinationTransferPrepared.json, test/data/notificationSourceTransferAtomic.json, test/data/notificationSourceTransferAtomic_TwoCases.json, test/data/notificationSourceTransferPrepared.json, test/data/paymentOneToOne.json, test/data/paymentSameExecutionCondition.json, test/notificationSpec.js, test/routeBuilderSpec.js, test/subscriptionSpec.js
In order to support different types of ledgers, the information that travels with the transfer should be ledger-agnostic. We've identified the minimum set of fields necessary to get the payment to its destination: `destinationAccount` and `destinationAmount`, called the ILP packet or ILP header.
This PR changes the format of the transfer memos to include the ILP header instead of the destination_transfer object as before.
This PR build on #159 which should be merged first.
Related PRs:
interledger/five-bells-notary#65
interledger/five-bells-shared#142
interledger/five-bells-sender#72
=> BREAKING: ILP Packet

schemas/Quote.json, src/lib/route-broadcaster.js, src/lib/route-builder.js, src/lib/routing-tables.js, src/models/quote.js, test/ilpQuoterSpec.js, test/routeBroadcasterSpec.js, test/routeBuilderSpec.js, test/routingTablesSpec.js
* If `explain` parameter is set to `true` during a quote, an additional info field will be included in the response
* The base rate will be included iff the quote is local
* Aggregating additional info when a multi hop payment needs to be defined further and is not yet implemented. No non-local quotes will not return additional info.
* More fields for fees, slippage, spread to be added at a later stage.
=> Explain parameter for /quote to get information about how amounts are computed

circle.yml
Otherwise, earlier versions will publish with the `latest` tag
https://docs.npmjs.com/cli/publish
=> ci: publish tagged package version for ilp_server_alpha branch

src/backends/ilp-quoter/index.js, src/lib/info-cache.js, src/services/backend.js, test/ilpQuoterSpec.js
feature: send ledger precision and scale to quoter when getting quote
The connector should send precision of the source or destination ledger
based on the quote value that needs to be computed (and rounded).
- If quote specifies source amount, then send the precision of the
receiving ledger
- If quote specifies receive amount, then send the precision of the source ledger
=> feature: send ledger precision and scale to quoter when getting quote

package.json, src/lib/multiledger.js, src/lib/sqliteStore.js, test/storeSpec.js
Changes multiledger and testPaymentExpiry so that ILP-Plugin-Virtual is able to be used in the connector. This includes adding a sqlite-based store in src/lib for persistence in ILP-Plugin-Virtual. ILP-Plugin-Virtual is also added as a dependency.
=> Fix: Support ILP-Plugin-Virtual

test/ilpQuoterSpec.js
Added a test for backend `ilpQuoterSpec.js`. A test already exists in `routeBuilderSpec.js`.
Testing the actual `/quote` endpoint would involve instantiating the app with a mock ilpQuoter backend which goes beyond unit testing I guess. Thoughts?
=> Test for additional_info field

src/lib/executeSourceTransfer.js, test/mocks/mockPlugin.js, test/paymentsSpec.js
This code currently expects `fulfillCondition` to resolve to a string, although this is not specified in the LedgerPlugin interface. Instead, the connector should give an error on a rejected promise.
=> fix: handle fulfillment reject instead of returning string

src/lib/config.js, src/lib/route-broadcaster.js, src/services/route-broadcaster.js, test/helpers/app.js
Feature flag for curve shifting. Some clients do not (yet) work with that feature. This flag allows to disable it until this is fixed. Should not impact other use cases since the feature is on by default.
=> Feature flag for route shifting (on by default)

src/lib/route-builder.js, test/routeBuilderSpec.js
the connector was stripping the ilp header before sending the last
transfer. the full ilp packet is useful for the recipient to check the
details of the incoming transfer against what was supposed to happen
(i.e. what was in the packet).
this changes the behavior to pass
through the whole ILP packet. this is also useful for when we switch to
binary, as it is arguably simpler for the connector to just forward on
the packet rather than stripping particular fields before sending it to
the receiver. if we do want to strip fields before handing the packet
off to the actual end user, the client libraries can do that.
requires https://github.com/interledger/five-bells-receiver/pull/4 for integration tests to pass.
=> feat: BREAKING pass through ILP packet

src/lib/config.js, src/lib/route-broadcaster.js, src/lib/route-builder.js, src/lib/routing-tables.js, src/services/route-broadcaster.js, src/services/routing-tables.js, test/helpers/app.js, test/quoteSpec.js, test/routeBroadcasterSpec.js, test/routeBuilderSpec.js
Tests will pass once https://github.com/interledger/five-bells-integration-test/pull/27 is merged.
This change makes quoting less pessimistic by using unshifted local routes for `findBestHopBy*`, (but still broadcasting the shifted routes) and always rounding in the connector's favor.
=> fix: make quoting less pessimistic

package.json, src/backends/fixerio-plus-coinmarketcap.js
Load exchange rate data from Coinmarketcap (and combine with Fixer.io) to support cryptocurrencies and fiat currencies alike.
=> feat: add a backend using coinmarketcap

src/lib/config.js, test/configSpec.js
The fields that `validateCredentialsEnv` checked were specific to `ilp-plugin-bells`, and shouldn't be required for other plugin types. Validating credentials should be the responsibility of the ledger plugins.
=> fix: remove credential validation

package.json
plugin bells now uses ledger metadata URLs to discover service locations
note this will not work with ledgers before 16.1.1 because of the bug
fixed in https://github.com/interledger/five-bells-ledger/commit/fd28a665cc35569a7cf562dc9996928a6a322ab8
=> feat: update to ilp-plugin-bells@7.0.0

package.json
to omit null values from transfers, set content-type for fulfillments, and don't auto-configure connector
=> fix: update ilp-plugin-bells to 7.0.3

.gitignore, src/lib/route-broadcaster.js, test/routeBroadcasterSpec.js
don't throw an error when broadcasting route to peer fails
=> fix: handle non-responsive peers

README.md, package.json, src/lib/config.js, src/lib/core.js, src/lib/route-broadcaster.js, src/lib/utils.js, test/configSpec.js, test/data/ledgerCredentials.json, test/ilpQuoterSpec.js, test/paymentsSpec.js, test/routeBroadcasterSpec.js, test/routeBuilderSpec.js
Removes `CONNECTOR_CREDENTIALS`, instead rolling those options into `CONNECTOR_LEDGERS`. Fixes a problem in the auto-generation of `CONNECTOR_PAIRS` which causes pairs to be generated in one direction only (would include `usd -> eur` but not `eur -> usd`). Updates the README to reflect these changes.
=> Feat: [BREAKING] improve PAIRS, LEDGERS, CREDENTIALS

scripts/ci-deploy.sh
`npm info` prints `undefined` on a nonexistant version, not an empty string. This problem was preventing `ilp-connector` from publishing to npm.
This was likely a change between node 4 and node 6, introduced in https://github.com/interledger/js-ilp-connector/commit/6a4b7a8de955db79413ff1d2f79950b4a0269b2e . It would explain why the most recent version on npm is 10.0.3.
=> Fix: fix the deploy script

package.json, src/app.js, src/common/log.js, test/helpers/log.js, test/routeBroadcasterSpec.js, test/routeBuilderSpec.js
Bunyan is causing issues during development due to the separate CLI transformer process. Riverpig is a cleaner, simpler logger. As a dependency it is 10x smaller than bunyan.
=> Switch logging from bunyan to riverpig

README.md, package.json, src/app.js
Fixes https://github.com/interledgerjs/ilp-connector/issues/249
This doesn't address the issue that Backends should supply route curves.
=> fix: allow BACKEND to be an external module name

src/models/quote.js, test/quoteSpec.js
Validating that the balance is greater than the sending amount will cause errors in many cases. First, if an account has a minimum allowed balance less than zero, it will cause the connector to break if its balance ever goes negative. Checking a minimum balance also would cause problems; some ledgers (such as trust-lines) may not have a static minimum balance.
If the connector's transaction is rejected by the ledger due to low balance, it will still cancel the previous transaction.
=> Fix: allow the connector to send on negative balance

src/app.js, src/models/subscriptions.js
Disable the timeout introduced by https://github.com/interledgerjs/ilp-plugin-bells/pull/74.
The timeout should be disabled because the ledger may just not have been started yet (see https://github.com/interledgerjs/ilp-connector/issues/248).
=> fix: disable plugin.connect() timeout

package.json
plugin-virtual isn't used anywhere in the connector directly. Having an outdated version routinely breaks the ILP Kit when there are updates.
=> Chore: remove plugin-virtual dependency

src/lib/pluginStore.js, test/storeSpec.js
The `Sequelize.STRING` type is limited to 255 characters.
=> Fix: allow long strings in plugin store

src/app.js, src/lib/route-broadcaster.js, test/modifyPluginSpec.js
The current `addPlugin` and `removePlugin` functions don't properly add/remove peers.
=> Fix: add and remove peers along with plugins

src/app.js, src/backends/fixerio/index.js, src/backends/one-to-one.js, src/lib/executeSourceTransfer.js, src/lib/route-builder.js, src/models/payments.js, src/models/subscriptions.js, test/paymentsSpec.js, test/routeBuilderSpec.js, test/subscriptionSpec.js
This will allow the backend to handle fees, making `transfer.depends_on` obsolete.
=> fix: call backend.submitPayment

src/lib/route-broadcaster.js
Currently, if broadcasting on a specific ledger fails, all broadcasting stops, because the interval never gets set.
Fixes #284.
=> fix: route broadcasting should survive a single bad ledger

src/backends/fixerio/index.js
Just a suggestion, because the `BigNumber Error: new BigNumber() not a number: undefined` exception is super annoying.
=> fix: fixerio: throw on getCurve if rates are undefined

package.json
five-bells-shared@21.2.0 disallows negative route coordinates, which we unintentionally rely on right now.
=> fix: use five-bells-shared@~21.1.0

src/lib/message-router.js
Connector shouldn't throw an exception if it receives requests that it's not familiar with. Other components listening to accounts might be trying to handle them.
=> chore: ignore unkown methods instead of throwing

src/lib/route-broadcaster.js, test/routeBroadcasterSpec.js
right now only connectors that are returned in the ledger info will be added as peers. this change makes it so all connectors listed in CONNECTOR_PEERS will be added, whether or not the ledger plugin knows about them
=> fix: add connectors from config, even if not in ledger info

src/lib/route-broadcaster.js, test/routeBroadcasterSpec.js
https://github.com/interledgerjs/ilp-connector/commit/a4c37b90a9123f3f59d53705213a86af0317765a added connector peers without the ledger prefix but that is necessary for route broadcasts to work
=> fix: connector peers must be full ILP addresses

package.json, src/lib/route-broadcaster.js, src/lib/routing-tables.js
Fix is based on an old version of connector so we can backport it.
Config routes were using the curve `[ [0, 0], [1, 1] ]`, which was causing any source/dest amounts above 1 to fail. Because the curve only defines what's in the domain but remote quotes determine the actual rate, it now should use `[ [0, 0], [Number.MAX_VALUE, Number.MAX_VALUE] ]`.
=> fix: use config routes for any input/output amount

src/lib/pluginStore.js, test/storeSpec.js
Dash is a special character in the regex square brackets
=> Fix: escape the dash in plugin store name regex

src/app.js, src/backends/fixerio/index.js, src/backends/one-to-one.js, test/helpers/app.js, test/mocks/mockPlugin.js, test/modifyPluginSpec.js, test/quoteSpec.js, test/routeBuilderSpec.js, test/routingTablesSpec.js, test/subscriptionSpec.js, test/tradingPairsSpec.js
When prepending a trustline as a hop, clip the liquidity curve to the maximum inbound transfer, so `plugin.maxBalance()-plugin.getBalance()`. This should help avoid a lot of the failed payments we're currently seeing when trying to use ilp-kit to pay each other back for lunch.
=> feat: liquidity routing

README.md, src/app.js, src/lib/config.js, src/lib/route-builder.js, test/configSpec.js, test/helpers/app.js, test/routeBuilderSpec.js
also allow the connector to be configured such that it will use the same transfer id for the destination as the source (even though this is not recommended)
=> feat: use secret to generate transfer ids

src/lib/route-builder.js, test/routeBuilderSpec.js
`plugin-virtual` requires the `from` parameter, so this should fix ilp-kit's broken integration tests once it is merged.
=> fix: sendTransfer({from})

src/backends/fixerio/index.js, src/backends/one-to-one.js
Using numbers can cause:
ERROR Couldn't add the peer to the connector { BigNumber Error: lt() number type has more than 15 significant digits: 9671611521766.432
at raise (/var/app/ilp-kit/node_modules/bignumber.js/bignumber.js:1198:25)
at new BigNumber (/var/app/ilp-kit/node_modules/bignumber.js/bignumber.js:262:21)
at BigNumber.P.lessThan.P.lt (/var/app/ilp-kit/node_modules/bignumber.js/bignumber.js:1572:35)
at FixerIoBackend.getCurve (/var/app/ilp-kit/node_modules/ilp-connector/src/backends/fixerio/index.js:124:47)
at getCurve.next (<anonymous>)
at onFulfilled (/var/app/ilp-kit/node_modules/co/index.js:65:19)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:169:7) name: 'BigNumber Error' }
=> fix: use strings when generating curves

src/app.js, src/lib/message-router.js
* `ilp-connector.listen()` needs to return a Promise so that ilp-kit knows when the connector is ready.
* Also adds a log line for when `handleRequest()` fails.
=> fix: listen() should return a Promise

src/app.js, src/lib/route-broadcaster.js
If the connector started before the ledgers, "connector ready" could print before both plugins were connected. The test would start, but there would be no routes.
With this patch, the connector will only print "connector ready" when all plugins are connected, so the test will pass.
=> fix: fix connector_first race condition

src/lib/ilp-errors.js, src/lib/route-builder.js, src/lib/testPaymentExpiry.js, src/models/payments.js, test/paymentsSpec.js
* Translate a plugin's `NotAcceptedError` on `sendTransfer()` to `T04: Insufficient Liquidity`.
* Also, "Insufficient Source Amount" is `R01`, not `R02`.
Related to https://github.com/interledgerjs/ilp-kit/issues/400
Depends on https://github.com/interledgerjs/five-bells-integration-test/pull/86 and https://github.com/interledgerjs/ilp-plugin-bells/pull/154
=> fix: return T04: Insufficient Liquidity

src/lib/quoter.js, src/lib/route-builder.js, test/routeBuilderSpec.js
When the incoming amount is higher than expected, don't forward this difference on to the next connector; instead, always pay as little as possible (based on the curve from next to final).
cc @emschwartz @justmoon
=> fix: greedy forwarding

src/lib/executeSourceTransfer.js, src/lib/ledgers.js, src/lib/utils.js, test/configSpec.js
Previously, the connector did not add pairs that would allow it to route a payment coming from ledger x back to that same ledger. And why would it? Ledgers were perfectly capable of directly routing that payment.
However, since the Interledger enlightenment, we may want to have the connector act as a ledger replacement. This mostly works, but for performance, we would like one plugin be able to represent multiple clients. Once again, this mostly works out of the box, except that the connector does not know how to deliver a payment if it's destination ledger is the same as its source.
This PR changes the connector such that it creates pairs for each ledger to itself by default.
=> Enable self-pairs by default

src/lib/quoter.js, src/lib/route-builder.js, test/paymentsSpec.js, test/routeBuilderSpec.js
As proposed in interledger/rfcs#313.
@michielbdejong [suggested](https://github.com/interledger/rfcs/issues/312#issuecomment-339663215) that overloading the existing packet format is a bad idea. In a general sense, I agree. As a practical matter, this patch is (as you can see below) very simple, breaks none of the existing tests (and doesn't break any existing ILP use cases) and allows us to build modern chunked/streaming payment transport layer protocols on our existing reference implementation. (Plan is that @emschwartz will start to work on back-porting the "ILP3" transport layer into the ilp module this week.)
I think the ultimate goal should be a cleaned-up ILPv2/BestEffort packet, where the amount is removed, see interledger/rfcs#323. However, I like the idea of experimenting with …
=> Use best rate when ILP packet amount is zero

src/schemas/Config.json
Since the default `minMessageWindow` is a generous 1000ms, a `maxHoldTime` of only 10s implies a maximum number of hops of nine. This PR increases the default to 30s, which corresponds to about 30s hops which should be plenty. If 30s turns out to be too high due to the free option problem, we can adjust it down again.
=> feat: increase default max hold time

package.json
The npm "prepack" hook runs when installing the repo from git (e.g. when the integration tests are run in CircleCI). This is necessary because the built javascript files aren't committed, only the typescript.
This + https://github.com/interledgerjs/five-bells-integration-test/pull/93 will fix https://github.com/interledgerjs/ilp-connector/pull/416 integration tests.
=> fix: add prepack build hook

README.md, package.json, src/middlewares/balance.ts, src/middlewares/rate-limit.ts, src/middlewares/stats.ts, src/services/accounts.ts, src/services/admin-api.ts, src/services/middleware-manager.ts, src/services/rate-backend.ts, src/services/stats.ts, src/types/middleware.ts, test/admin.test.js, test/helpers/app.js
Add endpoints to the admin API to expose info about accounts, balances, plugin throughput, and rates.
Minor fixes:
Fix README typo; enable eslint on tests (since they are in javascript, not typescript).
=> feat: extend admin API

src/routing/ccp-sender.ts, src/routing/dragon.ts, src/routing/utils.ts, src/services/forwarding-routing-table.ts, src/services/route-broadcaster.ts, test/route-broadcaster.test.js
Previously, connectors would broadcast a full history of their routing table changes:
```
1: g.u1 => g.u1
2: g.u2 => g.u1 g.u2
3: g.u2 withdrawn
```
However, if an update is overwritten by a later update, we can safely delete it. E.g. this log is equivalent:
```
1: g.u1 => g.u1
3: g.u2 withdrawn
```
Note that we can't delete update no.3 even though it is now a no-op for anyone downloading the table from scratch. This is because someone might have downloaded our routing table up to epoch 2 and they still need to know that we no longer serve this route.
Both route changes and route withdrawals can be removed from the log when a new entry for the same entry is added, regardless of whether the new entry is adding, changing, or removing the route. When adding a route update to the log, there …
=> Performance: Cleanup redundant routes

.gitignore, package.json, src/app.ts, src/middlewares/balance.ts, src/middlewares/rate-limit.ts, src/middlewares/stats.ts, src/schemas/Config.json, src/services/admin-api.ts, src/services/stats.ts, src/types/middleware.ts, test/admin.test.js, test/helpers/app.js
BREAKING: Admin API `/stats` endpoint uses new format
This change modifies the admin API as follows:
1. The `/stats` endpoint is a new more verbose format to better reflect the new data model for metrics.
2. There is a new `/metrics` endpoint for consumption by a Prometheus scraper job allowing the data to be recorded as time series and properly analyzed.
=> feat: use Prometheus-compatible metrics

src/services/accounts.ts, src/services/admin-api.ts, src/types/plugin.ts, test/admin.test.js, test/mocks/mockPlugin.js
Right now, the kinds of things that the Moneyd GUI can view at are pretty limited. We can only see the internals of the connector.
This feature allows us to look inside of the plugin and allow it to expose additional info and admin operations. It adds two optional functions to the plugin interface.
```ts
getAdminInfo (): Promise<object>
setAdminInfo (object): Promise<object> 
```
It also adds two endpoints to the connector's admin API.
```http
GET /accounts/:account_id
POST /accounts/:account_id
```
`getAdminInfo` resolves an object with information about the plugin's state. For an XRP plugin, for instance, it might return channel IDs and channel balances, along with overall XRP balance. You can get this information from the admin API. Moneyd GUI could display a nicely formatted interface …
=> Feat: add admin info interface to accounts

src/app.ts, src/services/accounts.ts
When you pass `log.warn` as a parameter to `debugPrint`, it then becomes an anonymous function as a variable and looses it's `this` context decoupling it away from `ConnectorLogger.prototype.warn`. Passing `log.warn.bind(log)` will retain the log's `this` context.
> **Example:**
[`https://repl.it/@roblav96/ilp-connector-logger-undefined-this`](https://repl.it/@roblav96/ilp-connector-logger-undefined-this)
=> Retain ConnectorLogger `this` context

src/middlewares/stats.ts, src/services/stats.ts
Labelling metrics with `triggeredBy` causes a memory leak because there are an unbounded number of ILP addresses that may be saved in memory.
Also fixes a typo: `s/AccountGuage/AccountGauge`.
=> fix: stats memory leak

src/services/accounts.ts
This is necessary for plugins that want to copy the options object before passing it to sub-plugins.
=> fix: use object properties for opts.{_store,_log}

src/controllers/ilp-prepare.ts, src/services/rate-backend.ts, src/types/backend.ts
- `controllers/ilp-prepare` - change `submitPayment` to `submitPacket`: always submit to backend whether packet type is fulfill, prepare, reject
- `types/backend` - add more params to `SubmitPaymentParams`: backend should receive more data
- `services/backend` - replace `this.getInfo` with `this.accounts`: backend should have access to more of the `accounts` api
- backends `ecb`, `one-to-one`, `randomizer`: update from using `this.getInfo` to `this.accounts`
=> feat: broaden scope of backend service

package-lock.json, package.json, src/app.ts, src/backends/ecb.ts, src/lib/utils.ts, src/middlewares/deduplicate.ts, src/middlewares/expire.ts, src/middlewares/rate-limit.ts, src/services/admin-api.ts, src/stores/leveldown.ts, tsconfig.json
Closes https://github.com/interledgerjs/ilp-connector/issues/480
This fixes errors when importing ILP Connector to the latest version of typescript. Also makes the type checking stricter by enabling `noImplicitAny`
This doesn't break anything if you're still importing from typescript 2.6
=> Update typescript version

README.md
The current Quickstart command is broken because the Connector does not stay running after issuing it.
This PR fixes this by enabling the AdminApi for this specific use-case. Without this additional directive, and because no accounts are defined in this quickstart command, there's nothing on the connector that's listening (no accounts and no admin API) and so there's nothing to keep the node process alive. With the admin API enabled it's running an http server, which will hold the connector process open.
=> Add `CONNECTOR_ADMIN_API=true` to Quickstart

src/services/admin-api.ts, src/services/stats.ts
As discussed on Slack, this is a PR to merge the metrics from the Prometheus ILP registry with the default registry and export it via the endpoint `/metrics`.
Prior to v22.2.0, the metrics export via `/metrics` used the Prometheus default registry that contains both metrics (ILP and nodejs/process) while >22.2.0 creates its own registry for the ILP metrics. This additional registry is only exported as JSON via the `/stats` endpoint, but not via `/metrics` anymore.
=> Merge Prometheus ILP metrics with default metrics

.circleci/config.yml
From circleci:
```
+ docker build -t interledger/js-ilp-connector --rm=false .
ERRO[0001] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: no such file or directory
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Exited with code 1
```
=> chore(circleci): try to fix docker

examples/example-using-LPI-v2.js, package.json
Fixes https://github.com/interledgerjs/ilp-connector/issues/500
`ilp-protocol-ildcp`'s `serializeIldcpRequest` requires an options object.
=> chore: pass options
